### ISSUE TITLE
Can't restore with forge paket restore

### ISSUE THREAD

**Issue by oivvio** [fsharp-editing/Forge#67] opened 2017-05-22 09:05 UTC
After creating a new project with forge, checking it out to git and then
checking it out again in a different location (same computer, so same mono version) I'm unable to run `forge paket restore` 

## Current Behavior
```
oivvio@blomma  forge paket restore
mono  "/tmp/minisuave/.paket/paket.bootstrapper.exe" 
Cannot open assembly '/tmp/minisuave/.paket/paket.bootstrapper.exe': No such file or directory.
Error while running '/tmp/minisuave/.paket/paket.bootstrapper.exe' with args: 
mono  "/tmp/minisuave/.paket/paket.exe" restore
Cannot open assembly '/tmp/minisuave/.paket/paket.exe': No such file or directory.
Error while running '/tmp/minisuave/.paket/paket.exe' with args: restore

```

## Possible Solution
I guess there's a step I need to run before running `forge paket restore` to install paket in the project.

I tried `forge update-version paket` but that gives me 

```
mono  "/tmp/minisuave/.paket/paket.bootstrapper.exe" 
Cannot open assembly '/tmp/minisuave/.paket/paket.bootstrapper.exe': No such file or directory.
Error while running '/tmp/minisuave/.paket/paket.bootstrapper.exe' with args:
```

## Your Environment

* Version used:

Forge 1.4.1

* Environment name and version (F#, .Net):

Mono JIT compiler version 5.0.0 

* Operating System and version:

Ubuntu 16.04

**Comment by oivvio** [comment] 2017-06-02 19:43
Turns out `.paket/paket.exe` is in `.gitignore` but it's needed for `forge paket restore` 
So an easy work around for the problem I was having is to simply remove it from `.gitignore`

**Comment by Krzysztof-Cieslak** [comment] 2017-06-03 10:26
The problem is not `.paket/paket.exe` but `.paket/paket.bootstrapper.exe` which used to be in `.gitignore`. This was fixed some time ago, refreshing templates should fix problem for the future new projects. For existing project, just download bootstrapper from Paket webpage, and make sure it's committed to repo.

**Closed by Krzysztof-Cieslak** 2017-06-03 10:26 UTC
